import localFont from "next/font/local";
import "@/app/Style/globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { ProductProvider } from "./(pages)/(dashboard)/product/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
      <ProductProvider>
        <SidebarProvider>
          {children}
        </SidebarProvider>
      </ProductProvider>
      </body>
    </html>
  );
}
